Metrics/ParameterLists:
  Max: 6

Naming/AccessorMethodName:
  Enabled: false
Naming/FileName:
  Enabled: false

Security/Eval:
  Enabled: false

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
