Metrics/MethodLength:
  Max: 12
Metrics/ParameterLists:
  Max: 8

Naming/AccessorMethodName:
  Enabled: false
Naming/FileName:
  Enabled: false

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
