language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - rbx-2
  - jruby-19mode
  - ruby-head
  - jruby-head
env:
  global:
    - EBAY_APP_ID=foo
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
